google_analytics:

title: Your site title
description: Your site description

plugins:
  - jekyll-seo-tag

exclude: [
  package.json,
  package-lock.json,
  postcss.config.js,
  tailwind.config.js,
  readme.md,
  assets/css/tailwind.config.css
]